[project]
name = "zs-releasenotes"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "feedgen>=1.0.0",
    "lxml>=6.0.2",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
]
